coopstube/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from coops import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('dashboard', views.dashboard, name='dashboard'), 
    #Auth
    path('signup', views.SignUp.as_view(), name="signup"),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name="logout"),
    #Coops
    path('coop/create', views.CreateCoop.as_view(), name='create_coop'),
    path('coop/<int:pk>', views.DetailCoop.as_view(), name='detail_coop'),
    path('coop/<int:pk>/update', views.UpdateCoop.as_view(), name='update_coop'),
    path('coop/<int:pk>/delete', views.DeleteCoop.as_view(), name='delete_coop'),
    #Videos
    path('coop/<int:pk>/addvideo', views.add_video, name='add_video'),
    path('video/search', views.video_search, name='video_search'),
    path('video/<int:pk>/delete', views.DeleteVideo.as_view(), name='delete_video'),
] 

coops/models.py
from django.db import models
from django.contrib.auth.models import User

class Coop(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    coop = models.ForeignKey(Coop, on_delete=models.CASCADE)

coops/forms.py
from .models import Video
from django import forms

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = [ 'url']
        labels = {'url':'YouTube Url'}

class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label='Search for Videos:')

coops/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from .models import Coop, Video
from .forms import VideoForm, SearchForm
import requests
from django.http import Http404, JsonResponse
import urllib 
from django.forms.utils import ErrorList
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

YOUTUBE_API_KEY = 'AIzaSyDgz0oNhLXGcDSD5zPN5QxGK0Ho4OUeVLY'

def home(request):
    recent_coops = Coop.objects.all().order_by('-id')[:3]
    popular_coops = [Coop.objects.get(pk=1), Coop.objects.get(pk=2), Coop.objects.get(pk=3)]
    return render(request, 'coops/index.html', {'recent_coops': recent_coops, 'popular_coops': popular_coops})

@login_required
def dashboard(request):
    coops = Coop.objects.filter(user=request.user)
    return render(request, 'coops/dashboard.html', {'coops':coops})

@login_required
def add_video(request, pk):
    form = VideoForm()
    search_form = SearchForm()
    coop = Coop.objects.get(pk=pk)
    if not coop.user == request.user:
        raise Http404

    if request.method == 'POST':

        filled_form = VideoForm(request.POST)
        if filled_form.is_valid():
            video = Video()
            video.coop = coop
            video.url = filled_form.cleaned_data['url']
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(f'https://www.googleapis.com/youtube/v3/videos?part=snippet&id={ video_id[0] }&key={ YOUTUBE_API_KEY }')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                video.title = title
                video.save()
                return redirect('detail_coop', pk)
            else:
                errors = form._errors.setdefault('url', ErrorList())
                errors.append('Needs to be a YouTube URL')

    return render(request, 'coops/add_video.html', {'form': form, 'search_form': search_form, 'coop': coop })

@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_term'])
        response = requests.get(f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=6&q={ encoded_search_term }&key={ YOUTUBE_API_KEY }')
        return JsonResponse(response.json())
    return JsonResponse({'error':'Not able to validate form'})


class DeleteVideo(LoginRequiredMixin, generic.DeleteView):
    model = Video
    template_name = 'coops/delete_video.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        if not video.coop.user == self.request.user:
            raise Http404
        return video


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/signup.html'

    # def form_valid(self, form):
    #     view = super(SignUp, self).form_valid(form)
    #     username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
    #     user = authenticate(username=username, password=password)
    #     login(self.request, user)
    #     return view


class login(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/login.html'


class CreateCoop(LoginRequiredMixin, generic.CreateView):
    model = Coop 
    fields = ['title']
    template_name = 'coops/create_coop.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreateCoop, self).form_valid(form)
        return redirect('dashboard')

class DetailCoop(generic.DetailView):
    model = Coop
    template_name = 'coops/detail_coop.html'

class UpdateCoop(LoginRequiredMixin, generic.UpdateView):
    model = Coop
    template_name = 'coops/update_coop.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        coop = super(UpdateCoop, self).get_object()
        if not coop.user == self.request.user:
            raise Http404
        return coop

class DeleteCoop(LoginRequiredMixin, generic.DeleteView):
    model = Coop
    template_name = 'coops/delete_coop.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        coop = super(DeleteCoop, self).get_object()
        if not coop.user == self.request.user:
            raise Http404
        return coop

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>CoopTv{% block title %} {% endblock %}</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="CoopTv video collections">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
</head>
  <body>

    {% include 'partials/shared/_navbar.html' %}
      {% block content %} {% endblock %}
    {% comment %} {% include 'partials/shared/_footer.html' %} {% endcomment %}


  </body>
</html>

templates/coops/add_video.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

<div class="card mt-5">
  <div class="card-body">

  <h2 class="lead purple-text">Add Video to Coop: {{ coop.title }}</h2>
  <form method="post" id="submit_video">
    {% csrf_token %}
    {% load widget_tweaks %}

    {% for field in form %}
    <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
      {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Add</button>
  </form>
  <br>

  <form>
    {% for field in search_form %}
    <div class="form-group">
      {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
    </div>
    {% endfor %}
  </form>
</div>
</div>
  <div id="search_results"></div>
  <script>
    var delayTimer;
    $('#id_search_term').keyup(function() {
      clearTimeout(delayTimer);
      $('#search_results').text('Loading...');
      delayTimer = setTimeout(function() {
        var text = $('#id_search_term').val();
        $.ajax({
          url: '/video/search',
          data: {
            'search_term': text
          },
          dataType: 'json',
          success: function(data) {
            var results = '';
            $('#search_results').text('');
            results += '<div class="row">';
            data['items'].forEach(function(video) {
              results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
              results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' + video['id']['videoId'] +
                '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
              results += '<div class="card-body"><p class="card-text">' + video['snippet']['title'] + '</p>';
              results += '<a href="#" class="btn btn-primary" onclick="addVideo(\'' + video['id']['videoId'] + '\')">Add</a></div></div></div>';

            });
            results += '</div>';
            $('#search_results').append(results);
          }
        });
      }, 1000);
    });

    function addVideo(video_id) {
      $('#id_url').val('https://www.youtube.com/watch?v=' + video_id);
      $('#submit_video').submit();
    }
  </script>

</div>
{% endblock %}

templates/coops/create_coop.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<div class="card mt-5">
  <div class="card-body">
<h2 class="lead purple-text">Create Coop</h2>
<form method="post">
  {% csrf_token %}

  {% load widget_tweaks %}
  {% for field in form %}
  <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
    {{ field.errors }}
    {{ field.label_tag }}
    {% render_field field class="form-control" %}
  </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary">Create</button>
</form>
</div>
</div>

</div>
{% endblock %}

templates/coops/dashboard.html
{% extends 'base.html' %}

{% block title %} | Dashboard {% endblock %}

{% block content %}
<div class="container">
  <div class="jumbotron card card-image my-jumb" style="background-image: url(https://mdbootstrap.com/img/Photos/Others/gradient1.jpg);">
  <div class="text-white py-5 px-4">
    <div>
      <h2 class="card-title h1-responsive pt-3 mb-5 font-bold"><strong>Welcome to your dashboard, {{user.username}} </strong></h2>
      <p class=" mb-5">Create and manage all your coops and videos
      </p>
      <a  href="{% url 'create_coop' %}" class="btn btn-outline-white btn-md"><i class="fas fa-clone left"></i>Create Coop</a>
    </div>
  </div>
</div>
  {% comment %} <div class="text-left addss">
  
         <h1 class="display-4 mt-5 pt-4 text-secondary">{{ user.username }}'s Coops  </h1> 
        <a class="icon-icon icon-icon purple-text" href="{% url 'create_coop' %}"> <i class="fas fa-plus-circle"></i> Create Coop</a>
   
  </div> {% endcomment %}
  {% for coop in coops %}
    <h2 class="vid-title mt-5"><a class="deep-purple-text" href="{% url 'detail_coop' coop.id %}">{{ coop.title }}</a></h2>
    <a class="icons-stuff purple-text" href="{% url 'delete_coop' coop.id %}"><i class="fas fa-trash"></i>Delete</a>
    <a class="icons-stuff purple-text" href="{% url 'update_coop' coop.id %}"><i class="far fa-edit"></i>Edit</a>
    <a class="icons-stuff purple-text" href="{% url 'add_video' coop.id %}"><i class="fas fa-plus-circle"></i>Add Video</a>
    <div class="row">
      {% for video in coop.video_set.all %}
      <div class="col-md-4 mt-3">
        <div class="card mb-4 shadow-sm">
          <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div class="card-body">
            <p class="card-text">{{ video.title }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/coops/delete_coop.html
{% extends 'base.html' %}
{% block content %}

<div class="container">

    <div class="card mt-5">
    <div class="card-body">
    <h2>Are you sure you want to delete this Coop?</h2>
    <form method="post">
     {% csrf_token %}
     {{ form }}
     <button type="submit" class="btn btn-danger">Delete Coop</button>
     </form>

     <br>
     <h2><a  class="purple-text" href="{% url 'detail_coop' coop.id %}">{{ coop.title }}</a></h2>
     </div>
     </div>
    </div>
{% endblock %}

templates/coops/delete_video.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

<div class="card mt-5">
<div class="card-body">

  <h2>Are you sure you want to delete this video?</h2>
   <p class="card-text">{{ video.title }}</p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>
</div>
</div>

  <div class="row">
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body">
          <p class="card-text">{{ video.title }}</p>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock %}

templates/coops/detail_coop.html
{% extends 'base.html' %}


{% block title %} | Welcome {% endblock %}

{% block content %}

<div class="container" >
    
 

{% if user.id == coop.user.id %}
    <h2><a href="{% url 'detail_coop' coop.id %}">{{ coop.title }}</a></h2>
<a href="{% url 'delete_coop' coop.id %}" class="btn btn-danger">Delete</a>
<a href="{% url 'update_coop' coop.id %}" class="btn btn-primary">Edit</a>
<a href="{% url 'add_video' coop.id %}" class="btn btn-primary">Add Video</a>
{% endif %}
    <div class="row">
      {% for video in coop.video_set.all %}
      <div class="col-md-4 mt-3">
        <div class="card mb-4 shadow-sm">
          <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div class="card-body">
            <p class="card-text">{{ video.title }}</p>
            {% if user.id == coop.user.id %}
            <a href="{% url 'delete_video' video.id %}" class="btn btn-danger">Delete</a>
            {% endif %}
               {% comment %} <h4>{{ coop.user.username }}</h4> {% endcomment %}
          </div>
        </div>
      </div>
      {% endfor %}
      </div>
</div>
  
{% endblock %}

templates/coops/index.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}

<main class="mt-5 pt-5">
    {% include 'partials/coops/_header.html' %}
    {% include 'partials/coops/_popular_coops.html' %}
    {% include 'partials/coops/_recent_coops.html' %}
</main>

{% endblock %} 

 

   

templates/coops/update_coop.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
<div class="card mt-5">
<div class="card-body">
    <h2 class="purple-text">Update Coop</h2>
    <form method="post">
     {% csrf_token %}
     {% load widget_tweaks %}
     {% for field in form %}

        <div class="form-group {% if field.errors %} alert aler-danger{% endif %}">
            {{ field.errors }}
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
        </div>

     {% endfor %}
    
     </form>
 <button type="submit" class="btn btn-primary">Save</button>
     <a href="{% url 'delete_coop' coop.id %}" class="btn btn-danger">Delete Hall</a>
     </div>
     </div>
</div> 
{% endblock %}

templates/partials/coops/_header.html
<div class="container">

            <!--Section: Jumbotron-->
            <section class="card wow fadeIn" style="background-image: url(https://mdbootstrap.com/img/Photos/Others/gradient1.jpg);">

                <!-- Content -->
                <div class="card-body text-white text-center py-5 px-5 my-5">

                    <h1 class="mb-4">
                        <strong>Welcome To CoopTv</strong>
                    </h1>
                    <p>
                        <strong>The best New Platform to store your favorite youtube videos into Coops</strong>
                    </p>
                    <p class="mb-4">
                        <strong>Create as many Coops as you like ALL FOR FREE</strong>
                    </p>
                    <a href="{% url 'signup' %}" class="btn btn-outline-white btn-lg">Create Free Account
                        {% comment %} <i class="fas fa-graduation-cap ml-2"></i> {% endcomment %}
                    </a>

                </div>
                <!-- Content -->
            </section>
            <!--Section: Jumbotron-->

templates/partials/coops/_popular_coops.html
<section class="text-center mt-3 pt-5 ">
  <h1 class="text-left mt-5 mb-3 display-5 purple-text">Popular Coops</h1>
   {% for coop in popular_coops %}
      <h2 class="text-left deep-purple-text"><a href="{% url 'detail_coop' coop.id %}" class="text-secondary">{{ coop.title }}</a></h2>
  <div class="row mb-4 wow fadeIn">
   

       {% for video in coop.video_set.all %}
        <div class="col-md-4 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <div class="card-body">
                    <p class="card-text">{{ video.title }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
       {% endfor %}         
    
</section>

templates/partials/coops/_recent_coops.html
<section class="text-center mt-5 pt-4 mb-5">
  <h1 class="text-left  purple-text mt-2 mb-3 display-5">Recent Coops</h1>
  {% for coop in recent_coops %}

<h2 class="text-left"><a href="{% url 'detail_coop' coop.id %}" class="text-secondary">{{ coop.title }}</a></h2>

  <div class="row">
    {% for video in coop.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body">
          <p class="card-text">{{ video.title }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
    </div>
  {% endfor %}
</section>

templates/partials/shared/_footer.html
<footer class="purple coop-footer">
  <div class="footer-copyright text-center py-3">© 2019 
    <a href="{% url 'home' %}"> CoopTv</a>
  </div>
</footer>

templates/partials/shared/_navbar.html
 <header>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark primary-color">
            <div class="container">

                <!-- Brand -->
                <a class="navbar-brand waves-effect" href="{% url 'home' %}" >
                    <strong class="">CoopTv</strong>
                </a>

                <!-- Collapse -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left -->
                    <ul class="navbar-nav ml-auto">
                       {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'dashboard' %}">{{user.username}}'s Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'create_coop' %}">Create Coop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'logout' %}" >Logout</a>
                        </li>
                        {% endif %}
                        {% if user.is_authenticated == False %}
                          <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'signup' %}" >Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'login' %}" >Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </nav>
        <!-- Navbar -->

    </header>